### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by jjhi11** [CrunchyData/pg_featureserv#151]
The default feature limit I am getting is 1000 with deploying the docker hub image to google cloud run. So I am trying to deploy a custom container via cloud run. I get this error though. 

Step 4/11 : ADD ./pg_featureserv .
ADD failed: file not found in build context or excluded by .dockerignore: stat pg_featureserv: file does not exist
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1

The only edit to the repo is to the config file to adjust the LimitMax. I am no docker pro and i'm stumped why it would work with the docker hub image and not a custom build.

**Comment by JakobMiksch** [comment]
Building a new Docker image is not necessary. You can simply mount a config file `pg_featureserv.toml` that is located in your filesystem. I ran it in docker-compose like this:  

```yaml
version: '3.8'
services:
    db:
      image: postgis/postgis:12-3.1
      environment:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
      ports:
        - "5432:5432"
    pg_featureserv:
        image: pramsey/pg_featureserv:20230711
        restart: unless-stopped
        environment:
          - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        ports:
          - "9000:9000"
        volumes:
          - ./pg_featureserv.toml:/config/pg_featureserv.toml
```

if you want to start a single docker container, your solution should be: (untested)

```shell
docker run -dt -e DATABASE_URL=postgresql://user:pass@host/dbname -p 9000:9000 -v $(pwd)/pg_featureserv.toml:/config/pg_featureserv.toml pramsey/pg_featureserv:latest
```
