### ISSUE TITLE
Load database URL to pg_featureserv container via secrets

### ISSUE THREAD

**Issue by RoryMMMM** [CrunchyData/pg_featureserv#81]
This is more of a feature request but it would be nice. 

I'm trying to not have my database user/password stored as environment variables or plain text config files and would rather have them stored as docker secrets. Docker-compose seems to not have a great way of translating secrets to environment vars inside the running container. The "standard workaround" seems to be to have the program look at a specified file to retrieve the sensitive config variables. Looks like that's the way it works in mysql, [postgres ](https://hub.docker.com/_/postgres) etc. 

So if I specified a docker secret, stored as a file, called "POSTGRES_URL_FILE" and then tried to run pg_featureserv it wouldn't work.

```
version: '3.8'
services:
  pg_featureserv:
    # Pg Featureserv: Lightweight PostGIS API tool
    # https://access.crunchydata.com/documentation/pg_featureserv/1.1.1/introduction/
    hostname: pg_featureserv
    image: pramsey/pg_featureserv:${PGFEATSERV_TAG}
    ports:
      - 9000:9000
    environment:
       DATABASE_URL: /run/secrets/POSTGRES_URL_FILE 
    secrets: 
      - POSTGRES_URL_FILE
secrets:
  POSTGRES_URL_FILE:
    file: ./secrets/db_url.txt
```

resulting in:
```

pg_featureserv_1   | time="2021-09-21T12:08:46Z" level=info msg="----  pg_featureserv - Version 1.1 ----------\n"
pg_featureserv_1   | time="2021-09-21T12:08:46Z" level=info msg="Using config file: DEFAULT"
pg_featureserv_1   | time="2021-09-21T12:08:46Z" level=info msg="Using database connection info from environment variable DATABASE_URL"
pg_featureserv_1   | time="2021-09-21T12:08:46Z" level=info msg="pg-featureserv\n"
pg_featureserv_1   | time="2021-09-21T12:08:46Z" level=fatal msg="cannot parse `/run/secrets/POSTGRES_URL_FILE`: failed to parse as DSN (invalid dsn)"
```

Any chance of allowing it to work? Or some other method of accepting docker secrets?
